In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]],dtype="int32")
print(a)

[[1 2 3]
 [4 5 6]]


In [2]:
a.dtype

dtype('int32')

In [3]:
a.ndim

2

In [4]:
a.shape

(2, 3)

In [5]:
a.itemsize

4

In [6]:
a.nbytes

24

In [7]:
a[0,0]

1

In [8]:
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
a[:,2]

array([3, 6])

In [10]:
a[0, 0:-1:1]

array([1, 2])

In [11]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
one=np.ones((2,2))
print(one)

[[1. 1.]
 [1. 1.]]


In [13]:
z=np.zeros((4,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
z[1:3,1:3]=one
print(z)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
arr=np.array([[1,2,3]])#[[2d array]][singlearray]
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
a=np.array([[1,2,3]])
b=a.copy()
b[0,2]=100
print(b)

[[  1   2 100]]


In [32]:
a=np.array([[1,2,3]])##it can do the various mathematical operations
b=a+2
print(b)

[[3 4 5]]


In [38]:
a=np.array([[30,90,120]])
b=np.cos(a)
print(b)


[[ 0.15425145 -0.44807362  0.81418097]]


In [43]:
a=np.ones((2,3))
print(a)
b=np.full((2,3),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]]


In [49]:
c=np.identity(3)
print(c)
d=np.linalg.det(c)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [57]:
statistics=np.array([[1,2,3]])
print(statistics)
x=np.min(statistics)
y=np.max(statistics,axis=1)
z=np.sum(statistics,axis=0)
print(x,y,z)


[[1 2 3]]
1 [3] [1 2 3]


In [73]:
before=np.array([[1,2,3],
                 [3,4,5]])
shape=np.shape(before)
print(shape)
print(before)
print(before.reshape(3,2))



(2, 3)
[[1 2 3]
 [3 4 5]]
[[1 2]
 [3 3]
 [4 5]]


In [80]:
#vertical stacking
stack1=np.array([[1,2,3]])
stack2=np.array([[3,4,5]])
print(np.vstack([stack1,stack2,stack1,stack2]))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [81]:
stack1=np.array([[1,2,3]])
stack2=np.array([[3,4,5]])
print(np.hstack([stack1,stack2]))

[[1 2 3 3 4 5]]


In [ ]:
##load from data np.genfromtext("hxn.txt",delimiter=",")
